# Solution: numpy

Voir le [User Guide](https://numpy.org/doc/stable/user/absolute_beginners.html#) de numpy

In [1]:
import numpy as np

## Tests

In [65]:
# TODO: Ecrire une fonction vérifiant si un tableau contient au moins un élément différent de 0

def not_all_zeros(a):
    return (a != 0).sum() > 0
    # return (a != 0).any()

x = np.array([1, 0, 0, 0])
y = np.array([0, 0, 0, 0])

assert not_all_zeros(x)
assert not not_all_zeros(y)

In [67]:
# TODO: Ecrire une fonction vérifiant qu'un tableau ne possède pas de valeurs nulles. On pourra utiliser la fonction np.isnan

def no_null_values(a):
    return not np.isnan(a).any()

x = np.array([1, 2, np.nan, 3])
y = np.array([4, 5, 6, 7])

assert not no_null_values(x)
assert no_null_values(y)

## Création de tableaux

In [68]:
# TODO: Créer trois tableaux contenant dix 0, dix 1 et dix 5

np.zeros(10), np.ones(10), np.ones(10) * 5

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [69]:
# TODO: créer une matrice identité de 3 x 3

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
# TODO: Creer un tableau de nombres de 30 à 70

np.arange(30, 70)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

In [71]:
# TODO: Creer un tableau de nombres pairs de 30 à 70

np.arange(30, 70, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

## Opérations sur les tableaux

In [61]:
# TODO : multiplier tous les membres d'un tableau par 5

a = np.array([1, 2, 3])
a * 5

array([ 5, 10, 15])

In [54]:
# TODO : comparer deux vecteurs de même dimension membre à membre pour vérifier s'ils sont identiques.

a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

assert (a == b).all()

## Nombres aléatoires

Consulter la documentation de [Generator](https://numpy.org/doc/stable/reference/random/generator.html). En particulier, étudiez les fonctions de génération disponibles

In [31]:
# On crée un générateur de nombres aléatoires (Generator)

rng = np.random.default_rng(0)

---
Voir la [documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html)

In [51]:
# TODO: Générer un nombre aléatoire entre entre 0 et 1

rng.random()

0.9811950400663443

---

Voir la [documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html)

In [50]:
# TODO: Générer un vecteur de 10 entiers aléatoires entre 9 et 20

rng.integers(low=9, high=20, size=10)

array([10, 10, 17, 19, 19, 16, 19, 18,  9, 10])

---

Voir la [documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.normal.html)

In [44]:
# TODO: Générer un tableau de 15 nombres aléatoires d'une distribution normale

x = rng.normal(size=15)
x

array([ 0.32896963, -0.25857255,  1.58347288,  1.32036099,  0.63335262,
       -2.20350988,  0.05202897,  0.68368619,  1.00396158, -0.61790704,
        1.82201136, -1.32043097, -0.66152802,  0.93504999,  0.04905461])

In [46]:
# TODO: Transformer le tableau précédent en matrice 3 x 5

X = x.reshape((3, 5))
X

array([[ 0.32896963, -0.25857255,  1.58347288,  1.32036099,  0.63335262],
       [-2.20350988,  0.05202897,  0.68368619,  1.00396158, -0.61790704],
       [ 1.82201136, -1.32043097, -0.66152802,  0.93504999,  0.04905461]])